FORMAT: 1A
HOST: http://keyrock
TITLE: Identity Manager GE - Keyrock Specification
DATE: 26 March 2018
VERSION: v1
APIARY_PROJECT: keyrock
SPEC_URL: http://ging.github.io/fiware-idm/api-spec/
GITHUB_SOURCE: https://github.com/ging/fiware-idm

# Identity Manager GE - Keyrock

Identity Manager (IdM) GE API specifications comply with existing standards for authentication and user and provide access information. The following sections provide pointers to those standards and, when applicable, details about how the RESTful binding work. 

This specification is intended for Service Consumers (with developement skills) and Cloud Providers. For the former, this document provides a full specification of how to interoperate with the Identity Management Service API. For the latter, this specification indicates the interface to be provided to the client application developers to provide the described functionalities. To use this information, the reader should first have a general understanding of the [Generic Enabler service](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/FIWARE.ArchitectureDescription.Security.IdentityManagement).

The API user should be familiar with:

* RESTful web services
* HTTP/1.1
* JSON data serialization formats.
* OAuth 2.0 

# Preface

## Editors

+ Álvaro Alonso González
+ Enrique García Navalón
+ Federico A. Fernández Moreno
+ Alejandro Pozo Huertas

## Copyright

Copyright © 2015-2016 by [UPM](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/UPM).

## License


This specification is licensed under the
[FIWARE Open Specification License (implicit patent license)](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/FI-WARE_Open_Specification_Legal_Notice_%28implicit_patents_license%29).


## Status

This is a work in progress and is changing on a daily basis.
Please send your comments to [FIWARE IdM Github Project](https://github.com/ging/fiware-idm/issues)

## Acknowledgements

The editors would like to express their gratitude to all the people that have contributed to this specification. 


#Group Keyrock API

## Authentication [/v1/auth/tokens]
In order to manage the Identity Manager through the API you must obtain an access token to be included in HTTP headers. There are two methods to obtain an access token.

### Create token with Password method [POST]
+ Request
    + Headers
    
            Content-Type: application/json
            
    + Body
    
            {
              "name": "alice@test.com",
              "password": "passw0rd"
            }
+ Response 201 (application/json)

    + Headers
    
        HTTP/1.1 201 Created
        X-Subject-Token: 04c5b070-4292-4b3f-911b-36a103f3ac3f
        Content-Type: application/json; charset=utf-8
        Content-Length: 74
        ETag: W/"4a-jYFzvNRMQcIZ2P+p5EfmbN+VHcw"
        Date: Mon, 19 Mar 2018 15:05:35 GMT
        Connection: keep-alive
        
    + Body
    
        {
            "token": {
                "methods": ["password"],
                "expires_at":"2018-03-20T15:05:35.697Z"
            }
        }


### Create token with Token method [POST]
+ Request
    + Headers
    
            Content-Type: application/json
            
    + Body
    
            {
              "token": "token_id"
            }
            
+ Response 201 (application/json)

    + Headers
    
        HTTP/1.1 201 Created
        X-Subject-Token: 04c5b070-4292-4b3f-911b-36a103f3ac3f
        Content-Type: application/json; charset=utf-8
        Content-Length: 74
        ETag: W/"4a-jYFzvNRMQcIZ2P+p5EfmbN+VHcw"
        Date: Mon, 19 Mar 2018 15:05:35 GMT
        Connection: keep-alive
        
    + Body
    
        {
            "token": {
                "methods": ["password"],
                "expires_at":"2018-03-20T15:05:35.697Z"
            }
        }
            

### Get token info [GET]
+ Request
    + Headers
    
            X-Auth-token: auth_token
            X-Subject-token: subj_token
            
            
+ Response 201 (application/json)

    + Headers
    
        HTTP/1.1 200 OK
        Content-Type: application/json; charset=utf-8
        Content-Length: 278
        ETag: W/"116-JwJR8Y5eFV2SDon0j1GE5yWyNx4"
        Date: Tue, 20 Mar 2018 15:23:21 GMT
        Connection: keep-alive

        
    + Body
    
        {
          "access_token": "f0a0a067-6341-4943-8225-45f794b3d94b",
          "expires": "2018-03-21T15:22:33.000Z",
          "valid": true,
          "User": {
            "id": "2d6f5391-6130-48d8-a9d0-01f20699a7eb",
            "username": "alice_new",
            "email": "alice@test.com",
            "date_password": "2018-03-20T12:12:09.000Z",
            "enabled": true,
            "admin": false
          }
        }


### Delete token [DELETE]
+ Request
    + Headers
    
            X-Auth-token: auth_token
            X-Subject-token: subj_token
            
            
+ Response 204 (application/json)
        
        
## Applications [/v1/applications]

Applications are registered in Keyrock and consume OAuth2 resources.

### List Applications [GET]
+ Request
    + Headers
    
            X-Auth-token: token

+ Response 200 (application/json)

    + Headers
    
        HTTP/1.1 200 Ok
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 303
        ETag: W/"12f-64q7xcRDNfw7c2xrc1r2S5EFS6k"
        Date: Tue, 20 Mar 2018 10:14:30 GMT
        Connection: keep-alive

    + Body

        {
          "applications": [
            {
              "id": "0fbfa58c-e5b6-41c3-b748-ab29f1567a9c",
              "name": "Test_application 2",
              "description": "Description",
              "image": "default",
              "url": "http://localhost",
              "redirect_uri": "http://localhost/login",
              "grant_type": "client_credentials,password,implicit,authorization_code,refresh_token",
              "response_type": "code,token",
              "token_types": "bearer,jwt,permanent",
              "client_type": null
            },
            {
              "id": "fd7fe349-f7da-4c27-b404-74da17641025",
              "name": "Test_application 1",
              "description": "description",
              "image": "default",
              "url": "http://localhost",
              "redirect_uri": "http://localhost/login",
              "grant_type": "password,authorization_code,implicit",
              "response_type": "code,token",
              "token_types": "bearer",
              "client_type": null
            }
          ]
        }

### Create an Application [POST]

+ Request (application/json)
    + Headers
            
            X-Auth-token: token
    
    + Body

        {
          "application": {
            "name": "Test_application 1",
            "description": "description",
            "redirect_uri": "http://localhost/login",
            "url": "http://localhost",
            "grant_type": [
              "authorization_code",
              "implicit",
              "password"
            ],
            "token_types": [
                "jwt",
                "permanent"
            ]
          }
        }


+ Response 201 (application/json)
    + Headers
    
        HTTP/1.1 201 Created
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 329
        ETag: W/"149-yQORsIAntQ0YHR5uCyLZhk7jTkg"
        Date: Tue, 20 Mar 2018 10:16:13 GMT
        Connection: keep-alive

    + Body
            
        {
          "application": {
            "id": "fd7fe349-f7da-4c27-b404-74da17641025",
            "secret": "9dc463cf-8318-4f65-bc02-778424fdfd77",
            "image": "default",
            "name": "Test_application 1",
            "description": "description",
            "redirect_uri": "http://localhost/login",
            "url": "http://localhost",
            "grant_type": "password,authorization_code,implicit",
            "token_types": "jwt,permanent",
            "jwt_secret": "3f1164da20d50c62",
            "response_type": "code,token"
          }
        }

## Application [/v1/applications/{application_id}]

+ Parameters
    + application_id - Id of the application.
    
### Read Application details [GET]
+ Request
    + Headers
        
            X-Auth-token: token
+ Response 200 (application/json)

    + Headers
    
        HTTP/1.1 200 Ok
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 407
        ETag: W/"197-biN1lSH/UM4L+dEtIoLYyOGteWE"
        Date: Tue, 20 Mar 2018 10:25:33 GMT
        Connection: keep-alive

    + Body
    
            {
                "application": {
                    "id": "0fbfa58c-e5b6-41c3-b748-ab29f1567a9c",
                    "name": "Test_application 2",
                    "description": "Description",
                    "secret": "61f5def7-bcf9-45b1-9c69-d0887e403737",
                    "url": "http://localhost",
                    "redirect_uri": "http://localhost/login",
                    "image": "default",
                    "grant_type": "client_credentials,password,implicit,authorization_code,refresh_token",
                    "response_type": "code,token",
                    "token_types": "bearer,jwt,permanent",
                    "jwt_secret": "3f1164da20d50c62",
                    "client_type": null,
                    "scope": null,
                    "extra": null
                }
            }

### Update an Application [PATCH]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    
    + Body

        {
            "application": {
                "name": "new name",
                "description": "new description",
                "redirect_uri": "new redirect uri",
                "token_types": ["permanent"]
                "grant_type": [
                    "authorization_code",
                    "password"
                ]
            }
        }

+ Response 200 (application/json)


    + Headers
    
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 170
        ETag: W/"aa-XCFRn1K54wlgPzun8PluFjYwCO0"
        Date: Tue, 20 Mar 2018 10:29:04 GMT
        Connection: keep-alive
    
    + Body
    
        {
          "values_updated": {
            "name": "new name",
            "description": "new description",
            "redirect_uri": "new redirect uri",
            "grant_type": "password,authorization_code",
            "token_types": "bearer,permanent",
            "jwt_secret": null,
            "response_type": "code"
          }
        }
### Delete an Application [DELETE]
+ Request
    + Headers
            
            X-Auth-token: token
            
+ Response 204 (application/json)

# Users [/v1/users]

### List Users [GET]
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 200 (application/json)

    + Headers
    
        HTTP/1.1 200 Ok
        Content-Type: application/json; charset=utf-8
        Content-Length: 378
        ETag: W/"17a-/TnzfhPjjd4IG4D1u38zPZiSIL0"
        Date: Tue, 20 Mar 2018 10:08:27 GMT
        Connection: keep-alive

    + Body

        {
          "users": [
            {
              "id": "2d6f5391-6130-48d8-a9d0-01f20699a7eb",
              "username": "alice",
              "email": "alice@test.com",
              "enabled": true,
              "gravatar": false,
              "date_password": "2018-03-20T09:31:07.000Z",
              "description": null,
              "website": null
            },
            {
              "id": "admin",
              "username": "admin",
              "email": "admin@test.com",
              "enabled": true,
              "gravatar": false,
              "date_password": "2018-03-20T08:40:14.000Z",
              "description": null,
              "website": null
            }
          ]
        }

### Create a User [POST]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    
    + Body
        {
            "user": {
                "username": "alice",
                "email": "alice@test.com",
                "password": "passw0rd"
            }
        }

+ Response 201 (application/json)

    + Headers

        HTTP/1.1 201 Created
        Content-Type: application/json; charset=utf-8
        Content-Length: 205
        ETag: W/"cd-hbCwPDJrO5NvpsY2pqY6Qhlf/do"
        Date: Tue, 20 Mar 2018 09:31:07 GMT
        Connection: keep-alive

    + Body

        {
            "user": {
                "id":"2d6f5391-6130-48d8-a9d0-01f20699a7eb",
                "image":"default",
                "gravatar":false,
                "enabled":true,
                "admin":false,
                "username":"alice",
                "email":"alice@test.com",
                "date_password":"2018-03-20T09:31:07.104Z"
            }
        }

## User [/v1/users/{user_id}]

+ Parameters
    + user_id - Id of the user.

### Read info about a User [GET]
+ Request
    + Headers
        
            X-Auth-token: token

+ Response 200 (application/json)


    + Headers
        HTTP/1.1 200 Ok
        Content-Type: application/json; charset=utf-8
        Content-Length: 239
        ETag: W/"ef-346BFly5PUZzqso7/DhcynciNPs"
        Date: Tue, 20 Mar 2018 10:34:20 GMT
        Connection: keep-alive

    + Body
    
        {
            "user": {
                "id": "2d6f5391-6130-48d8-a9d0-01f20699a7eb",
                "username": "alice",
                "email": "alice@test.com",
                "enabled": true,
                "admin": false,
                "image": "default",
                "gravatar": false,
                "date_password": "2018-03-20T09:31:07.000Z",
                "description": null,
                "website": null
            }
        }

### Update a User [PATCH]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    
    + Body
        { 
            "user": {
              "username": "new_alice",
              "password": "passw0rd_new"
            }
        }
+ Response 200 (application/json)

    + Headers
    
        HTTP/1.1 200 OK
        Content-Type: application/json; charset=utf-8
        Content-Length: 72
        ETag: W/"48-NygV9BIfH5juflD+icW6fPFuBkA"
        Date: Tue, 20 Mar 2018 10:38:59 GMT
        Connection: keep-alive

    + Body

        {
            "values_updated": {
                "username": "alice_new",
                "email": "alice_new@test.com"
            }
        }
### Delete a User [DELETE]
+ Request
    + Headers
        
            X-Auth-token: token

+ Response 204 (application/json)

# Organizations [/v1/organizations]

### List Organizations [GET]
+ Request
    + Headers
        
            X-Auth-token: token

+ Response 200 (application/json)


    + Headers
    
        HTTP/1.1 201 Created
        Content-Type: application/json; charset=utf-8
        Content-Length: 355
        ETag: W/"163-0eDqBVBTEbKRQmAm6AtzDLXVigI"
        Date: Tue, 20 Mar 2018 10:45:36 GMT
        Connection: keep-alive

    + Body

        {
          "organizations": [
            {
              "role": "owner",
              "Organization": {
                "id": "33cf4d3c-8dfb-4bed-bf37-7647f45528ec",
                "name": "Test organization 2",
                "description": "description 2",
                "image": "default",
                "website": null
              }
            },
            {
              "role": "owner",
              "Organization": {
                "id": "3e20722f-d420-422d-89ba-3ae87bc1c0cd",
                "name": "Test organization",
                "description": "description",
                "image": "default",
                "website": null
              }
            }
          ]
        }

### Create an Organization [POST]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    
    + Body
    
            {
                "organization": {
                    "name": "Test organization",
                    "description": "description"
                }
            } 

+ Response 201 (application/json)

    + Headers
    
        HTTP/1.1 201 Created
        Content-Type: application/json; charset=utf-8
        Content-Length: 135
        ETag: W/"87-mQPZWVCWNw1jTeBUp2u6DfQUBXg"
        Date: Tue, 20 Mar 2018 10:41:14 GMT
        Connection: keep-alive

    + Body

        {
          "organization": {
            "id": "3e20722f-d420-422d-89ba-3ae87bc1c0cd",
            "image": "default",
            "name": "Test organization",
            "description": "description"
          }
        }

## Organization [/v1/organizations/{organization_id}]

+ Parameters
    + organization_id - Id of the organization.

### Read info about an Organization [GET]
+ Request
    + Headers
        
            X-Auth-token: token

+ Response 200 (application/json)

    + Headers

        HTTP/1.1 201 Created
        Content-Type: application/json; charset=utf-8
        Content-Length: 150
        ETag: W/"96-Gd8UZNti5b/l9AK7zLVUgoPzoSg"
        Date: Tue, 20 Mar 2018 10:46:47 GMT
        Connection: keep-alive
    
    + Body
        {
          "organization": {
            "id": "3e20722f-d420-422d-89ba-3ae87bc1c0cd",
            "name": "Test organization",
            "description": "description",
            "website": null,
            "image": "default"
          }
        }

### Update an Organization [PATCH]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    
    + Body
    
        {
          "organization": {
            "description": "new description",
            "website": "http://test.com"
          }
        }

+ Response 200 (application/json)
    
    + Headers
    
        HTTP/1.1 200 OK
        Content-Type: application/json; charset=utf-8
        Content-Length: 80
        ETag: W/"50-SLhFvXhKe+sDolh13Q+2u5eotYw"
        Date: Tue, 20 Mar 2018 10:48:45 GMT
        Connection: keep-alive
    
    + Body
    
        {
          "values_updated": {
            "description": "new description",
            "website": "http://test.com"
          }
        }

### Delete an Organization [DELETE]

+ Request
    + Headers
        
            X-Auth-token: token
+ Response 204 (application/json)

## Roles [/v1/applications/{application_id}/roles]

+ Parameters
    + application_id - Id of the application.

### List Roles [GET]
+ Request
    + Headers
        
            X-Auth-token: token

+ Response 200 (application/json)
    
    + Headers
    
    HTTP/1.1 200 OK
    X-Powered-By: Express
    Content-Type: application/json; charset=utf-8
    Content-Length: 209
    ETag: W/"d1-00jqKKxgEvBT2U3J3v7Jttp5bOU"
    Date: Tue, 20 Mar 2018 11:13:38 GMT
    Connection: keep-alive

    + Body
    
        {
          "roles": [
            {
              "id": "purchaser",
              "name": "Purchaser"
            },
            {
              "id": "provider",
              "name": "Provider"
            },
            {
              "id": "ee2ec16f-694b-447f-b61a-e293b6fe5f7b",
              "name": "role 2"
            },
            {
              "id": "33fd15c0-e919-47b0-9e05-5f47999f6d91",
              "name": "role 1"
            }
          ]
        }

### Create a Role [POST]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    
    + Body
        
            {
              "role": {
                "name": "role 1"
              }
            }

+ Response 201 (application/json)

    + Headers

        HTTP/1.1 201 Created
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 147
        ETag: W/"93-gmWMlkuHssLlhgsbkRsYJjI1ZpE"
        Date: Tue, 20 Mar 2018 10:56:16 GMT
        Connection: keep-alive

    + Body
            {
              "role": {
                "id": "33fd15c0-e919-47b0-9e05-5f47999f6d91",
                "is_internal": false,
                "name": "role 1",
                "oauth_client_id": "fd7fe349-f7da-4c27-b404-74da17641025"
              }
            }

## Role [/v1/applications/{application_id}/roles/{role_id}]

+ Parameters
    + application_id - Id of the application.
    + role_id - Id of the role.

### Read Role details [GET]
+ Request
    + Headers
    
            X-Auth-token: token
            
+ Response 200 (application/json)
    
    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 147
        ETag: W/"93-jWdaZFK7V/AOFD7WOIM0aZePmqg"
        Date: Tue, 20 Mar 2018 11:21:19 GMT
        Connection: keep-alive
    
    + Body
    
        {
          "role": {
            "id": "33fd15c0-e919-47b0-9e05-5f47999f6d91",
            "name": "role 1",
            "is_internal": false,
            "oauth_client_id": "fd7fe349-f7da-4c27-b404-74da17641025"
          }
        }

### Update a Role [PATCH]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    
    + Body

            {
              "role": {
                "name": "test_role_new",
                "application_id": "2222"
              }
            }

+ Response 200 (application/json)

    + Headers
    
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 43
        ETag: W/"2b-pM4WlfxN6zpTuxeiYjs7ZBMAimM"
        Date: Tue, 20 Mar 2018 11:24:07 GMT
        Connection: keep-alive

    + Body
    
        {
          "values_updated": {
            "name": "new role name"
          }
        }
    

### Delete a Role [DELETE]
+ Request
    + Headers
        
            X-Auth-token: token
+ Response 204 (application/json)

## Permissions [/v1/applications/{application_id}/permissions]

+ Parameters
    + application_id - Id of the application.

### List Permissions [GET]
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 200 (application/json)
    
    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 816
        ETag: W/"330-B4K+xvKY9Z0W5Qhy4XfXIxsJnwU"
        Date: Tue, 20 Mar 2018 11:41:23 GMT
        Connection: keep-alive
    
    
    + Body
        {
          "permissions": [
            {
              "id": "6",
              "name": "Get and assign only public owned roles",
              "description": null,
              "action": null,
              "resource": null,
              "xml": null
            },
            {
              "id": "5",
              "name": "Get and assign all public application roles",
              "description": null,
              "action": null,
              "resource": null,
              "xml": null
            },
            {
              "id": "4",
              "name": "Manage authorizations",
              "description": null,
              "action": null,
              "resource": null,
              "xml": null
            },
            {
              "id": "3",
              "name": "Manage roles",
              "description": null,
              "action": null,
              "resource": null,
              "xml": null
            },
            {
              "id": "2",
              "name": "Manage the application",
              "description": null,
              "action": null,
              "resource": null,
              "xml": null
            },
            {
              "id": "15ca810b-27d1-44a1-8491-a3fb4b6bc6f3",
              "name": "permission 1",
              "description": null,
              "action": "GET",
              "resource": "login",
              "xml": null
            },
            {
              "id": "1",
              "name": "Get and assign all internal application roles",
              "description": null,
              "action": null,
              "resource": null,
              "xml": null
            }
          ]
        }

### Create a Permission [POST]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    
    + Body

            {
              "permission": {
                "name": "permission 1",
                "action": "GET",
                "resource": "login",
                "is_regex": false
              }
            }

+ Response 201 (application/json)
    + Headers
        HTTP/1.1 201 Created
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 193
        ETag: W/"c1-WkjxOsda9h0YVjVe6wfJ3/BB5/E"
        Date: Tue, 20 Mar 2018 11:34:41 GMT
        Connection: keep-alive
        
    + Body
    
            {
              "permission": {
                "id": "15ca810b-27d1-44a1-8491-a3fb4b6bc6f3",
                "is_internal": false,
                "name": "permission 1",
                "action": "GET",
                "resource": "login",
                "is_regex": false,
                "oauth_client_id": "fd7fe349-f7da-4c27-b404-74da17641025"
              }
            }

## Permission [/v1/applications/{application_id}/permissions/{permission_id}]

+ Parameters
    + application_id - Id of the application.
    + permission_id - Id of the permission.

### Read Permission details [GET]
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 200 (application/json)

    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 223
        ETag: W/"df-8dskjqxwg2z2vTSGP00GOfWr7ak"
        Date: Tue, 20 Mar 2018 11:42:26 GMT
        Connection: keep-alive

    + Body

            {
              "permission": {
                "id": "15ca810b-27d1-44a1-8491-a3fb4b6bc6f3",
                "name": "permission 1",
                "description": null,
                "is_internal": false,
                "action": "GET",
                "resource": "login",
                "xml": null,
                "oauth_client_id": "fd7fe349-f7da-4c27-b404-74da17641025"
              }
            }

### Update a Permission [PATCH]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    
    + Body

            {
              "permission": {
                "name": "new name permission",
                "description": "new description permission",
                "xml": "<permission>...</permission>"
              }
            }

+ Response 200 (application/json)
    
    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 109
        ETag: W/"6d-DcRDt9VL8q5NI3uqNXNrX+2Kq0U"
        Date: Tue, 20 Mar 2018 11:45:49 GMT
        Connection: keep-alive

        
    + Body
        {
          "values_updated": {
            "name": "new name permission",
            "description": "new description permission",
            "xml": "xml rule"
          }
        }
 
  
### Delete a Permission [DELETE]

+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 204 (application/json)


## Pep Proxies [/v1/applications/{application_id}/pep_proxies]

+ Parameters
    + application_id - Id of the application.


### Info Pep Proxy [GET]
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 200 (application/json)
    
    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 126
        ETag: W/"7e-WPTcZsaLk+L8CA5OdIqizFHVrPw"
        Date: Tue, 20 Mar 2018 11:57:37 GMT
        Connection: keep-alive
    
    
    + Body
        {
          "pep_proxy": {
            "id": "pep_proxy_2d19d297-e555-4e3a-a18d-22deda37036a",
            "oauth_client_id": "fd7fe349-f7da-4c27-b404-74da17641025"
          }
        }

### Create a Pep Proxy [POST]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token

+ Response 201 (application/json)
    + Headers
    
        HTTP/1.1 201 Created
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 129
        ETag: W/"81-pV8lmjYRuvS5Nc/SlKF+oCjMPlo"
        Date: Tue, 20 Mar 2018 11:56:18 GMT
        Connection: keep-alive

    + Body
    
        {
          "pep_proxy": {
            "id": "pep_proxy_2d19d297-e555-4e3a-a18d-22deda37036a",
            "password": "pep_proxy_950468f7-4198-42e1-8f41-4b1f8c5bc1f2"
          }
        }

### Reset Password of Pep Proxy [PATCH]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    

+ Response 200 (application/json)
    + Headers
        
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 65
        ETag: W/"41-U+BN5OW2bt+63vlUf0I9i/DAZ6M"
        Date: Tue, 20 Mar 2018 11:58:45 GMT
        Connection: keep-alive
  
    + Body
    
        {
            "new_password":"pep_proxy_3b2c8791-71b9-444a-b8c7-00d37cf35149"
        }
    

### Delete Pep Proxy [DELETE]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token
    

+ Response 204 (application/json)


## Iot Agents [/v1/applications/{application_id}/iot_agents]

+ Parameters
    + application_id - Id of the application.


### List of Iot Agents [GET]
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 200 (application/json)
    
    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 181
        ETag: W/"b5-JcuFa5VxfeRl0gl4ZrpOvxi6mHM"
        Date: Tue, 20 Mar 2018 12:03:26 GMT
        Connection: keep-alive
    
    + Body
        {
          "iot_agents": [
            {
              "id": "iot_sensor_47886fa2-883e-4550-bb56-0138ae9862b7"
            },
            {
              "id": "iot_sensor_74df472c-0fd1-4b8a-8f13-c6848307bc7d"
            },
            {
              "id": "iot_sensor_f95fc041-7102-4be7-8948-37fb571afa89"
            }
          ]
        }

### Create an Iot Agent [POST]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token

+ Response 201 (application/json)
    + Headers
    
        HTTP/1.1 201 Created
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 125
        ETag: W/"7d-33tQwa1x8d+8o71baUJyd7SFNUM"
        Date: Tue, 20 Mar 2018 12:01:48 GMT
        Connection: keep-alive

    + Body
    
        {
          "iot_agent": {
            "id": "iot_sensor_47886fa2-883e-4550-bb56-0138ae9862b7",
            "password": "iot_sensor_14569214-60d7-44d1-856c-ec8d8967aba2"
          }
        }


## Iot Agent [/v1/applications/{application_id}/iot_agents/{iot_agent_id}]

+ Parameters
    + application_id - Id of the application.
    + iot_agent_id - Id of the iot agent.

### Read Iot agent details [GET]
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 200 (application/json)

    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 121
        ETag: W/"79-PJ1MWYYk87AQio+Y/RZiMeOCRbU"
        Date: Tue, 20 Mar 2018 12:07:34 GMT
        Connection: keep-alive


    + Body

        {
          "iot_agent": {
            "id": "iot_sensor_47886fa2-883e-4550-bb56-0138ae9862b7",
            "oauth_client_id": "fd7fe349-f7da-4c27-b404-74da17641025"
          }
        }

### Reset Password of Iot Agent [PATCH]

+ Request (application/json)
    + Headers
        
            X-Auth-token: token

+ Response 200 (application/json)
    
    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 66
        ETag: W/"42-hPGur0etQ8aToU1LaPV+T1XO4Wo"
        Date: Tue, 20 Mar 2018 12:08:26 GMT
        Connection: keep-alive
        
    + Body
        {
          "new_password": "iot_sensor_9d209e51-bff1-4a20-a0f1-d75706f95b04"
        }
    

### Delete an Iot Agent [DELETE]

+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 204 (application/json)


## Role - Permission Relationships [/v1/applications/{application_id}/roles/{role_id}/permissions]

+ Parameters
    + application_id - Id of the application. 
    + role_id - Id of the role.

### List permissions associated to a role [GET]
+ Request
    + Headers
            
            X-Auth-token: token
+ Response 200 (application/json)
    
    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 475
        ETag: W/"1db-abmPwZLikwp2EbYVmU/UKdHtbGE"
        Date: Tue, 20 Mar 2018 12:15:29 GMT
        Connection: keep-alive

    + Body

        {
          "role_permission_assignments": [
            {
              "id": "15ca810b-27d1-44a1-8491-a3fb4b6bc6f3",
              "is_internal": false,
              "name": "new name permission",
              "description": "new description permission",
              "action": null,
              "resource": null,
              "xml": "xml rule"
            },
            {
              "id": "3",
              "is_internal": true,
              "name": "Manage roles",
              "description": null,
              "action": null,
              "resource": null,
              "xml": null
            },
            {
              "id": "1",
              "is_internal": true,
              "name": "Get and assign all internal application roles",
              "description": null,
              "action": null,
              "resource": null,
              "xml": null
            }
          ]
        }

## Role - Permission Relationship [/v1/applications/{application_id}/roles/{role_id}/permissions/{permission_id}]

+ Parameters
    + application_id - Id of the application.
    + role_id - Id of the role.
    + permission_id - Id of the permission.

### Assign a permission to a role [PUT]
+ Request (application/json)
    + Headers
        
            X-Auth-token: token
            
+ Response 201

    + Headers
        HTTP/1.1 201 Created
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 102
        ETag: W/"66-G5t4RaonrlcbX68lBuXLPzS+Glc"
        Date: Tue, 20 Mar 2018 12:18:41 GMT
        Connection: keep-alive
    
    + Body
    
        {
          "role_permission_assignments": {
            "role_id": "33fd15c0-e919-47b0-9e05-5f47999f6d91",
            "permission_id": "4"
          }
        }

### Remove a permission from a role [DELETE]
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 204 (application/json)


## Authorized users in an application [/v1/applications/{application_id}/users]
+ Parameters
    + application_id - Id of the application.
    

### List users in an application [GET]

+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 200 (application/json)

    + Headers
        
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 310
        ETag: W/"136-lW/H57r3jyK+ObyFOlWMB5tMuNU"
        Date: Tue, 20 Mar 2018 12:27:09 GMT
        Connection: keep-alive
        
    + Body
    
        {
          "role_user_assignments": [
            {
              "user_id": "2d6f5391-6130-48d8-a9d0-01f20699a7eb",
              "role_id": "provider"
            },
            {
              "user_id": "admin",
              "role_id": "purchaser"
            },
            {
              "user_id": "2d6f5391-6130-48d8-a9d0-01f20699a7eb",
              "role_id": "ee2ec16f-694b-447f-b61a-e293b6fe5f7b"
            },
            {
              "user_id": "admin",
              "role_id": "ee2ec16f-694b-447f-b61a-e293b6fe5f7b"
            }
          ]
        }

## Roles of User in an Application [/v1/applications/{application_id}/users/{user_id}/roles]

+ Parameters
    + application_id - Id of the application.
    + user_id - Id of the user.

### List users role assignments [GET]
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 200 (application/json)
    
    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 199
        ETag: W/"c7-kciYHLq/V20GkqNyzgr7HDzrWI4"
        Date: Tue, 20 Mar 2018 12:29:34 GMT
        Connection: keep-alive
    
    + Body
        {
          "role_user_assignments": [
            {
              "user_id": "2d6f5391-6130-48d8-a9d0-01f20699a7eb",
              "role_id": "provider"
            },
            {
              "user_id": "2d6f5391-6130-48d8-a9d0-01f20699a7eb",
              "role_id": "ee2ec16f-694b-447f-b61a-e293b6fe5f7b"
            }
          ]
        }

## Role - User Relationship in an Application [/v1/applications/{application_id}/users/{user_id}/roles/{role_id}]

+ Parameters
    + user_id - Id of the user.
    + application_id - Id of the application.
    + role_id - Id of the role.

### Assign a role to a user [PUT]
+ Request (application/json)
    + Headers
        
            X-Auth-token: token
            
+ Response 201

    + Headers
        HTTP/1.1 201 Created
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 155
        ETag: W/"9b-PTfLJchMB1s6mXINkQh6OJQnSgY"
        Date: Tue, 20 Mar 2018 12:31:58 GMT
        Connection: keep-alive

    + Body
        
        {
          "role_user_assignments": {
            "role_id": "purchaser",
            "user_id": "2d6f5391-6130-48d8-a9d0-01f20699a7eb",
            "oauth_client_id": "fd7fe349-f7da-4c27-b404-74da17641025"
          }
        }


### Remove a role assignment from a user [DELETE]

+ Request
    + Headers
        
            X-Auth-token: token

+ Response 204


## Authorized Organizations in an application [/v1/applications/{application_id}/organizations]
+ Parameters
    + application_id - Id of the application.
    

### List organizations in an application [GET]

+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 200 (application/json)

    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 798
        ETag: W/"31e-yAFZkeaD7GA4Xo4F6dAyMc/FISM"
        Date: Tue, 20 Mar 2018 12:37:51 GMT
        Connection: keep-alive

    + Body
    
        {
          "role_organization_assignments": [
            {
              "organization_id": "33cf4d3c-8dfb-4bed-bf37-7647f45528ec",
              "role_organization": "owner",
              "role_id": "purchaser"
            },
            {
              "organization_id": "33cf4d3c-8dfb-4bed-bf37-7647f45528ec",
              "role_organization": "owner",
              "role_id": "ee2ec16f-694b-447f-b61a-e293b6fe5f7b"
            },
            {
              "organization_id": "33cf4d3c-8dfb-4bed-bf37-7647f45528ec",
              "role_organization": "member",
              "role_id": "33fd15c0-e919-47b0-9e05-5f47999f6d91"
            },
            {
              "organization_id": "3e20722f-d420-422d-89ba-3ae87bc1c0cd",
              "role_organization": "owner",
              "role_id": "provider"
            },
            {
              "organization_id": "3e20722f-d420-422d-89ba-3ae87bc1c0cd",
              "role_organization": "owner",
              "role_id": "33fd15c0-e919-47b0-9e05-5f47999f6d91"
            },
            {
              "organization_id": "3e20722f-d420-422d-89ba-3ae87bc1c0cd",
              "role_organization": "member",
              "role_id": "ee2ec16f-694b-447f-b61a-e293b6fe5f7b"
            }
          ]
        }


## Roles of Organization in an Application [/v1/applications/{application_id}/organizations/{organization_id}/roles]
+ Parameters
    + organization_id - Id of the organization.
    + application_id - Id of the application.

### List organizations role assignments [GET]
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 200 (application/json)
    
    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 332
        ETag: W/"14c-Itun6PzsweI15qednKd5+tG7Oh0"
        Date: Tue, 20 Mar 2018 12:39:20 GMT
        Connection: keep-alive

    + Body
        {
          "role_organization_assignments": [
            {
              "organization_id": "33cf4d3c-8dfb-4bed-bf37-7647f45528ec",
              "role_id": "purchaser"
            },
            {
              "organization_id": "33cf4d3c-8dfb-4bed-bf37-7647f45528ec",
              "role_id": "ee2ec16f-694b-447f-b61a-e293b6fe5f7b"
            },
            {
              "organization_id": "33cf4d3c-8dfb-4bed-bf37-7647f45528ec",
              "role_id": "33fd15c0-e919-47b0-9e05-5f47999f6d91"
            }
          ]
        }

## Role - Organization Relationship in an Application [/v1/applications/{application_id}/organizations/{organization_id}/roles/{role_id}/organization_roles/{organization_role_id}]

+ Parameters
    + organization_id - Id of the organization.
    + application_id - Id of the application.
    + role_id - Id of the role.
    + organization_role_id - Id of organization role.

### Assign a role to a organization [PUT]
+ Request (application/json)
    + Headers
        
            X-Auth-token: token
            
+ Response 201

    + Headers
        
        HTTP/1.1 201 Created
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 198
        ETag: W/"c6-6eTVB6vyiwH6XKLZ3pLYYDXFMm4"
        Date: Tue, 20 Mar 2018 12:41:47 GMT
        Connection: keep-alive
        
    + Body
        
        {
          "role_organization_assignments": {
            "role_id": "provider",
            "organization_id": "33cf4d3c-8dfb-4bed-bf37-7647f45528ec",
            "oauth_client_id": "fd7fe349-f7da-4c27-b404-74da17641025",
            "role_organization": "owner"
          }
        }


### Remove a role assignment from an organization [DELETE]

+ Request
    + Headers
        
            X-Auth-token: token

+ Response 204


## Members of an organization [/v1/organizations/{organization_id}/users]

+ Parameters
    + organization_id - Id of the organization.


### List members [GET]

+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 201
    
    + Headers
        
        HTTP/1.1 200 OK
        Content-Type: application/json; charset=utf-8
        Content-Length: 240
        ETag: W/"f0-3G8Dv2NqT3KMGuO+jRta+nJMnJk"
        Date: Tue, 20 Mar 2018 12:47:26 GMT
        Connection: keep-alive
        
    + Body
        
        {
          "organization_users": [
            {
              "user_id": "2d6f5391-6130-48d8-a9d0-01f20699a7eb",
              "organization_id": "3e20722f-d420-422d-89ba-3ae87bc1c0cd",
              "role": "owner"
            },
            {
              "user_id": "admin",
              "organization_id": "3e20722f-d420-422d-89ba-3ae87bc1c0cd",
              "role": "member"
            }
          ]
        }
        


## User - Organization Relationships [/v1/organizations/{organization_id}/users/{user_id}/organization_roles]

+ Parameters
    + organization_id - Id of the organization.
    + user_id - Id of the user.

### Info of user organization relationship [GET]        
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 201

    + Headers
        HTTP/1.1 200 OK
        Content-Type: application/json; charset=utf-8
        Content-Length: 114
        ETag: W/"72-/fZonAf/VJOEZ94bshoBRSVQzmE"
        Date: Tue, 20 Mar 2018 12:51:28 GMT
        Connection: keep-alive
        
    + Body
    
        {
          "organization_user": {
            "user_id": "admin",
            "organization_id": "3e20722f-d420-422d-89ba-3ae87bc1c0cd",
            "role": "member"
          }
        }


## User - Organization Relationship [/v1/organizations/{organization_id}/users/{user_id}/organization_roles/{organization_role_id}]

+ Parameters
    + organization_id - Id of the organization.
    + user_id - Id of the user.
    + organization_role_id - Id of the organization role.

### Create relationship [PUT]        
+ Request (application/json)
    + Headers
        
            X-Auth-token: token
            
+ Response 201

    + Headers
    
        HTTP/1.1 201 Created
        Content-Type: application/json; charset=utf-8
        Content-Length: 125
        ETag: W/"7d-lt1JE+QQNKxkfaswZ+ZRWXj2vdk"
        Date: Tue, 20 Mar 2018 12:55:58 GMT
        Connection: keep-alive
        
    + Body
    
        {
          "user_organization_assignments": {
            "role": "owner",
            "user_id": "admin",
            "organization_id": "3e20722f-d420-422d-89ba-3ae87bc1c0cd"
          }
        }

### Delete relationship [DELETE] 
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 204

## Trusted Applications [/v1/applications/{application_id}/trusted_applications]

+ Parameters
    + application_id - Id of the application. 

### List trusted applications associated to an application [GET]
+ Request
    + Headers
            
            X-Auth-token: token
+ Response 200 (application/json)
    
    + Headers
        HTTP/1.1 200 OK
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 299
        ETag: W/"12b-fgVfRrc8fzRhPLgAGLWe+LLPg74"
        Date: Wed, 01 Aug 2018 11:34:42 GMT
        Connection: keep-alive

    + Body

        {
            "trusted_applications": [
                "8692ec57-8514-4ef6-a347-3d1ac6409f79",
                "78b4763f-139a-4820-a42b-3e265fb9d56e",
                "462ee067-f10a-4c9c-aefe-079038830043",
                "6781fd6c-9dd3-46d7-bdcc-4ca2af1ae42d",
            ]
        }

## Trusted Applications [/v1/applications/{application_id}/trusted_applications/{trustedApplicationId}]

+ Parameters
    + application_id - Id of the application.
    + trustedApplicationId - Id of the application to be added as trusted.

### Add trusted application [PUT]
+ Request (application/json)
    + Headers
        
            X-Auth-token: token
            
+ Response 201
    
    + Headers
        HTTP/1.1 201 Created
        X-Powered-By: Express
        Content-Type: application/json; charset=utf-8
        Content-Length: 123
        ETag: W/"7b-uwB1nhIkCNnU+e+LWcHAN4IO5XQ"
        Date: Wed, 01 Aug 2018 11:38:01 GMT
        Connection: keep-alive
    
    + Body
    
        {
            "oauth_client_id": "3e34cbf6-3579-4e54-878a-0a406962ac36",
            "trusted_oauth_client_id":"0118ccb7-756e-42f9-8a19-5b4e83ca8c46"
        }

### Remove trusted application from an application [DELETE]
+ Request
    + Headers
        
            X-Auth-token: token
            
+ Response 204 (application/json)

## Service Provider [/v1/service_providers/configs]

### Read Service Provider Configuration [GET]

"Information" provides the number of total users, total organizations, and the number of applications.
+ Request
    + Headers
        
            X-Auth-token: token

+ Response 200 (application/json)

    + Headers
    
        HTTP/1.1 201 Created
        Content-Type: application/json; charset=utf-8
        Content-Length: 77
        ETag: W/"4d-XGO2xqHcxBbtv7+72qxVUUJvMT4"
        Date: Tue, 20 Mar 2018 12:57:50 GMT
        Connection: keep-alive
        
    + Body
    
        {
          "information": {
            "totalUsers": 2,
            "totalOrganizations": 2,
            "totalApplications": 4
          }
        }

        
